name: Fly Deploy

on:
  push:
    branches:
    - deploy-gitactions

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
    - name: Chequeo del codigo
      uses: actions/checkout@v3

    - name: Instalar las dependencias
      run: npm install

    - name: ejecutar test
      run: npm run test

    - name: crear imagen de docker
      run: docker build -t nodeSami:latest .
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
    - uses: actions/checkout@v4
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
